movieproject/movieapp/urls.py
from . import views
from django.urls import path

app_name='movieapp'

urlpatterns = [
    path('',views.index, name="index"),
    path('movie/<int:movie_id>/',views.detail,name="DETAILS"),
    path('add/', views.add_movie, name="add_movie"),
    path('update/<int:id>/',views.update, name='UPDATE'),
    path('delete/<int:id>/',views.delete, name='DELETE')
]

movieproject/movieproject/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("movieapp.urls"))
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

movieproject/movieapp/models.py
from django.db import models

# Create your models here.
class Movie(models.Model):
   name=models.CharField(max_length=250)
   desc=models.TextField()
   year=models.IntegerField()
   Img=models.ImageField(upload_to='gallery')

   def __str__(self):
      return self.name

movieproject/movieapp/forms.py
from django import forms
from .models import Movie


class MovieForm(forms.ModelForm):
    class Meta:
        model=Movie
        fields=['name','desc','year','Img']

movieproject/movieapp/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect

# Create your views here.
from .forms import MovieForm
from .models import Movie




def index(request):
    movie=Movie.objects.all()
    context={
        'movie_list': movie
    }

    return render(request,"index.html",context)

def detail(request,movie_id):
    movie=Movie.objects.get(id=movie_id)
    return render(request,"details.html",{'movie':movie})

def add_movie(request):
    if request.method=="POST":
        name = request.POST.get('name',)
        desc = request.POST.get('desc',)
        year = request.POST.get('year',)
        Img = request.FILES['Img']
        movie=Movie(name=name,desc=desc,year=year,Img=Img)
        movie.save()
    return  render(request,'add.html')

def update(request,id):
    movie=Movie.objects.get(id=id)
    form=MovieForm(request.POST or None, request.FILES, instance=movie)
    if form.is_valid():
        form.save()
        return redirect ('/')
    return render(request,'edit.html',{"form":form, 'movie':movie})

def delete(request,id):
    if request.method=='POST':
        movie=Movie.objects.get(id=id)
        movie.delete()
        return  redirect('/')
    return render(request,'delete.html')

movieproject/templates/add.html
{% extends 'base.html' %}
{% block body %}


<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
  <div style="padding:50px; ">
    <input type="text" name="name" placeholder="Move name"><br>
    <br>
    <input type="text" name="desc" placeholder="Move desc"><br>
    <br>
    <input type="text" name="year" placeholder="Move year"><br>
    <br>
    <input type="file" name="Img" ><br>
    <br>
    <input type="submit">
  </div>
</form>


{% endblock %}

movieproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'style.css' %}">




</head>
<body>
<!-- Image and text -->
<nav class="navbar navbar-dark bg-dark navbar-expand-lg">
  <a class="navbar-brand" href="#">
    Online Movie Store
  </a>

    <a class="btn btn-outline-warning btn-lg btn-float-right" href="{% url 'movieapp:add_movie' %}">add new move</a>



</nav>
{% block body %}
{% endblock %}

</body>
</html>

movieproject/templates/delete.html
{% extends 'base.html' %}
{% block body %}
<form method="post">
    {% csrf_token %}
    <h3><b>Are you want to delete this movie</b></h3>
    <input type="submit">
</form>
{% endblock %}

movieproject/templates/details.html
{% extends 'base.html' %}
{% block body %}
<body>
<div class="container" >
    <div class="dd">
    <div class="row">
        <div class="col-md-6">
           <img src ="{{movie.Img.url}}" width="450" height="450"><br>
        </div>

        <div class="col-md-6">
            <h1>{{movie.name}}</h1>
            {{movie.desc}}
            {{movie.year}} <br>
            <a class="btn btn-dark" href="{% url 'movieapp:UPDATE' movie.id %}">update</a> <br>
            <a class="btn btn-danger" href="{% url 'movieapp:DELETE' movie.id %}">Delete</a>
        </div>
    </div>
    </div>
</div>
</body>


{% endblock %}

movieproject/templates/edit.html
{% extends 'base.html' %}
{% block body %}

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit">
</form>

{% endblock %}

movieproject/templates/index.html
{% extends 'base.html' %}
{% block body %}

<div class="container" >

    <div class="row" >
        {% for i in movie_list %}
        <div class="col-md-3">
        <div class="card"  >
          <img class="card-top-image" src="{{i.Img.url}}" alt="Card image cap"  height="250" >
            <div class="card-body">
            <h5 class="card-title">{{i.name}}</h5>

            <a href="{% url 'movieapp:DETAILS' i.id %}" class="btn btn-primary">view detailes</a>
            </div>
        </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}